name: Update

on:
  workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          const result = await github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: 'UAV_server',
            event_type: 'dependency_update',}
          })
          console.log(result);
